# Generated by Django 5.2.14 on 2026-05-30 23:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Kasa Adı')),
                ('para_birimi', models.CharField(choices=[('try', 'TRY — Türk Lirası'), ('usd', 'USD — Amerikan Doları'), ('eur', 'EUR — Euro'), ('btc', 'BTC — Bitcoin'), ('eth', 'ETH — Ethereum'), ('usdt', 'USDT — Tether'), ('usdc', 'USDC — USD Coin'), ('sol', 'SOL — Solana'), ('bnb', 'BNB — Binance Coin'), ('xrp', 'XRP — Ripple'), ('doge', 'DOGE — Dogecoin')], default='try', max_length=10, verbose_name='Para Birimi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelledigi_kasalar', to=settings.AUTH_USER_MODEL, verbose_name='Son güncelleyen')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_kasalar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Kasa',
                'verbose_name_plural': 'Kasalar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='KasaHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10, verbose_name='Hareket Tipi')),
                ('tutar', models.DecimalField(decimal_places=8, help_text='Kasanın para biriminde tutar', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Tutar')),
                ('kur_try', models.DecimalField(decimal_places=4, help_text='1 birim = X TRY (işlem tarihindeki kur)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Kur (TRY)')),
                ('tutar_try', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='TL Karşılığı')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelledigi_kasa_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='Son güncelleyen')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='finans.kasa', verbose_name='Kasa')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_kasa_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'Kasa Hareketi',
                'verbose_name_plural': 'Kasa Hareketleri',
                'ordering': ['-tarih', '-olusturulma'],
            },
        ),
    ]
